services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak_user -d keycloak_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "BionicPRO"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "admin"
      LDAP_READONLY_USER: "false"
      LDAP_RFC2307BIS_SCHEMA: "true"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
      - ./ldap/config.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-config.ldif
    networks:
      - app-network
    command: --copy-service --loglevel debug
    healthcheck:
      test: ["CMD-SHELL", "ldapsearch -x -H ldap://localhost:389 -D cn=admin,dc=example,dc=com -w admin -b dc=example,dc=com"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8090:80"
    depends_on:
      openldap:
        condition: service_healthy
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
    command: 
      - start-dev
    ports:
      - "8080:8080"
    depends_on:
      keycloak_db:
        condition: service_healthy
      openldap:
        condition: service_healthy
    networks:
      - app-network

  crm_db:
    image: postgres:13
    environment:
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
      POSTGRES_DB: crm_db
    volumes:
      - ./sql/init_crm.sql:/docker-entrypoint-initdb.d/init_crm.sql
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crm_user -d crm_db"]
      interval: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: clickhouse_password
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./sql/init_clickhouse.sql:/docker-entrypoint-initdb.d/init_clickhouse.sql
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 5s
      retries: 5

  airflow_db:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      retries: 5

  airflow-init:
    build: 
      context: ./airflow
      dockerfile: Dockerfile
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    depends_on:
      airflow_db:
        condition: service_healthy

  airflow:
    build: 
      context: ./airflow
      dockerfile: Dockerfile
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_CONN_CRM_POSTGRES=postgresql://crm_user:crm_password@crm_db:5432/crm_db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8081:8080"
    command: bash -c "airflow webserver & airflow scheduler"
    depends_on:
      airflow-init:
        condition: service_completed_successfully  # Ждем полного завершения инициализации
      airflow_db:
        condition: service_healthy
      crm_db:
        condition: service_healthy
      clickhouse:
        condition: service_healthy

  keycloak-import:
    image: quay.io/keycloak/keycloak:21.1
    networks:
      - app-network
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm-clean.json:/tmp/realm-clean.json
      - ./keycloak/ldap-component.json:/tmp/ldap-component.json
      - ./keycloak/ldap-role-mapper.json:/tmp/ldap-role-mapper.json
      - ./keycloak/import.sh:/tmp/import.sh
      - ./keycloak/setup-otp-user1.sh:/tmp/setup-otp-user1.sh
    depends_on:
      - keycloak
    entrypoint: /bin/bash
    command: /tmp/import.sh

  backend:
    build:
      context: ./backend/bionicpro-auth
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    volumes:
      - aspnet-keys:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Keycloak__BaseUrl=http://keycloak:8080
      - Keycloak__Realm=reports-realm
      - Keycloak__ClientId=reports-api
      - Keycloak__ClientSecret=oNwoLQdvJAvRcL89SydqCWCe5ry1jMgq
      - Keycloak__TokenEndpoint=/protocol/openid-connect/token
      - Keycloak__LogoutEndpoint=/protocol/openid-connect/logout
      - Keycloak__UserInfoEndpoint=/protocol/openid-connect/userinfo
      - Session__TimeoutMinutes=60
      - Session__CookieName=KeycloakSession
    depends_on:
      - keycloak-import
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_KEYCLOAK_URL=http://localhost:8080
      - REACT_APP_KEYCLOAK_REALM=reports-realm
      - REACT_APP_KEYCLOAK_CLIENT_ID=reports-frontend
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres-keycloak-data:
  aspnet-keys:
  ldap-data:
  ldap-config:

networks:
  app-network:
    driver: bridge