services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
    command: 
      - start-dev
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
    networks:
      - app-network

  keycloak-import:
    image: quay.io/keycloak/keycloak:21.1
    depends_on:
      - keycloak
    networks:
      - app-network
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm-export.json:/tmp/realm-export.json
    entrypoint: >
      /bin/bash -c "
        echo 'Waiting for Keycloak to start...' &&
        sleep 15 &&
        echo 'Importing realm...' &&
        /opt/keycloak/bin/kcadm.sh config truststore --trustpass $KEYCLOAK_TRUSTSTORE_PASSWORD &&
        /opt/keycloak/bin/kcadm.sh config credentials --server http://keycloak:8080 --realm master --user admin --password admin &&
        /opt/keycloak/bin/kcadm.sh create realms -f /tmp/realm-export.json ||
        /opt/keycloak/bin/kcadm.sh update realms/reports-realm -f /tmp/realm-export.json &&
        echo 'Import completed!' &&
        exit 0
      "

  backend:
    build:
      context: ./backend/bionicpro-auth
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    volumes:
      - aspnet-keys:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Keycloak__BaseUrl=http://keycloak:8080
      - Keycloak__Realm=reports-realm
      - Keycloak__ClientId=reports-api
      - Keycloak__ClientSecret=oNwoLQdvJAvRcL89SydqCWCe5ry1jMgq
      - Keycloak__TokenEndpoint=/protocol/openid-connect/token
      - Keycloak__LogoutEndpoint=/protocol/openid-connect/logout
      - Keycloak__UserInfoEndpoint=/protocol/openid-connect/userinfo
      - Session__TimeoutMinutes=60
      - Session__CookieName=KeycloakSession
    depends_on:
      - keycloak
      - keycloak-import
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_KEYCLOAK_URL=http://localhost:8080
      - REACT_APP_KEYCLOAK_REALM=reports-realm
      - REACT_APP_KEYCLOAK_CLIENT_ID=reports-frontend
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres-keycloak-data:
  aspnet-keys: 

networks:
  app-network:
    driver: bridge